### ISSUE TITLE
You don't have access

### ISSUE THREAD

**Issue by Simran93504** [kshitijofficial/Dgdrive3.0#2]
I am always getting "You don't have access" even while displaying my own data.

**Comment by ankurdg107** [comment]
Same error

**Comment by Simran93504** [comment]
Please update me whenever you found the cause. I am also trying

**Comment by varunpallikonda** [comment]
> I am always getting "You don't have access" even while displaying my own data.

Same error

**Comment by nitish-cse** [comment]
> first you have to give access to  the account from which you want to access data , then confirm the transaction in your metamask pupup , after  confirmed you can  get data by pasting the address  above the get data section

**Comment by Ash-mit17** [comment]
use account.toString( ) account was returning an array

**Comment by kshitijofficial** [comment]
I have now updated the README. Please read Usage section.
